services:
  jekyll:
    build: .
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
      - node_modules_cache:/app/node_modules
    stdin_open: true

volumes:
  bundle_cache:
  node_modules_cache:
