name: Jekyll site CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Read .tool-versions
      uses: marocchino/tool-versions-action@v1
      id: versions

    - uses: actions/setup-node@v3
      with:
        node-version: ${{steps.versions.outputs.nodejs}}
        cache: 'npm'
    - run: npm install

    - name: Build
      uses: jerryjvl/jekyll-build-action@v1

    - name: Deploy to Static Host 01
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -avzr --delete
        path: _site/
        remote_path: /var/www/website/
        remote_host: ${{ secrets.DEPLOY_STATIC_SITE_HOST01 }}
        remote_user: ${{ secrets.DEPLOY_STATIC_SITE_USER }}
        remote_key: ${{ secrets.DEPLOY_STATIC_SITE_KEY }}

    - name: Deploy to Static Host 02
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -avzr --delete
        path: _site/
        remote_path: /var/www/website/
        remote_host: ${{ secrets.DEPLOY_STATIC_SITE_HOST02 }}
        remote_user: ${{ secrets.DEPLOY_STATIC_SITE_USER }}
        remote_key: ${{ secrets.DEPLOY_STATIC_SITE_KEY }}

    - name: Deploy to Static Host 03
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -avzr --delete
        path: build/
        remote_path: /var/www/website/
        remote_host: ${{ secrets.DEPLOY_STATIC_SITE_HOST03 }}
        remote_user: ${{ secrets.DEPLOY_STATIC_SITE_USER01 }}
        remote_key: ${{ secrets.DEPLOY_STATIC_SITE_KEY01 }}
