name: Jekyll site CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Read .tool-versions
      uses: marocchino/tool-versions-action@v1
      id: versions

    - uses: actions/setup-node@v3
      with:
        node-version: ${{steps.versions.outputs.nodejs}}
        cache: 'npm'
    - run: npm install

    - name: Build
      uses: jerryjvl/jekyll-build-action@v1

    - name: Tailscale
      uses: tailscale/github-action@v2
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
        version: '1.50.1'
        tags: tag:static-sites

    - name: Deploy to Static Sites Host
      uses: burnett01/rsync-deployments@6.0.0
      with:
        switches: -avzr --delete
        path: _site/
        remote_path: /var/www/website/
        remote_host: ${{ secrets.DEPLOY_STATIC_SITE_HOST }}
        remote_user: ${{ secrets.DEPLOY_STATIC_SITE_USER }}
        remote_key: ${{ secrets.DEPLOY_STATIC_SITE_KEY }}

    - name: Purge BunnyCDN cache
      uses: eayllon/bunnycdn-purge-cache@253ab627f8e743b4d7f96e7020e8bc04377ac49d
      with:
        accessKey: ${{ secrets.BUNNY_API_KEY }}
        zoneID: ${{ secrets.BUNNY_ZONE_ID }}
